### ISSUE TITLE
Support for EXO V2

### ISSUE THREAD

**Issue by n2x4** [PwC-IR/Office-365-Extractor#1]
As 365 tenants start to lock down the ability to interface with basic auth and lack of MFA, are there plans to migrate the extractor to support EXO V2?

**Comment by PwC-IR** [comment]
Hi n2x4,

Sorry I wasn't able to get back to you sooner. 

We are currently running into the same problem at some of our clients. We are still looking into a possible solution, when using EXO V2 the session will end after one hour, resulting in the script returning errors and the need for re-authentication. This is a big problem since most data collections we do take multiple hours to complete.

We raised a Github issue at Microsoft around this problem: 
https://github.com/MicrosoftDocs/office-docs-powershell/issues/5457

We received the following response:
_"When you use the Exchange Online Remote PowerShell Module, your session will end after one hour, which can be problematic for long-running scripts or processes. To avoid this issue, use Trusted IPs to bypass MFA for connections from your intranet. Trusted IPs allow you to connect to Exchange Online PowerShell from your intranet using the old instructions at Connect to Exchange Online PowerShell. Also, if you have servers in a data center, be sure to add their public IP addresses to Trusted IPs as described here."_

Unfortunately, we have not yet found a solution to make the script work without using Trusted IPs etc. If you have any suggestions in making the script better and work with modern authentication feel free to reach out.
